### ISSUE TITLE
Shit frank doesn't like

### ISSUE THREAD

**Issue by francoislapierremessier** [JonathanSerafini/chef-nginx_resources#1]
Because frank likes to bitch about things

**Comment by JonathanSerafini** [comment]
Ahahaha !

**Comment by francoislapierremessier** [comment]
`unless node['nginx_resources']['source']['use_existing_user']
  user node['nginx']['user'] do
    system true
    shell  '/bin/false'
    home   '/var/www'
  end
end`

Shouldn't that use a not_if check within the ressource instead?

**Comment by JonathanSerafini** [comment]
Thought about that for use_existing_user, but I want to make sure we don't clash with anyone else having defined the resource with the same name previously.

**Comment by francoislapierremessier** [comment]
Oh wait, why the hell is that resource called ['nginx']['user'] since that's undefined and outside of your namespace? Wouldn't that blow up when used unless that attribute is defined to www-data?

Searching 69 files for "['nginx']"

/Users/francois.lapierremessier/Chef/cookbooks/chef-nginx_resources/recipes/install_user.rb:
    2  #
    3  unless node['nginx_resources']['source']['use_existing_user']
    4:   user node['nginx']['user'] do
    5      system true
    6      shell  '/bin/false'

1 match in 1 file

**Comment by JonathanSerafini** [comment]
Fixed in 08961a54ca0ef96715a8211a7c2590bc14bfc506

**Comment by francoislapierremessier** [comment]
Which takes us back to shouldn't we use not_if and if someone redefines that value AND uses the default runlist then they're just stupid and should use the providers you've made instead?

**Comment by francoislapierremessier** [comment]
I get that you want to future-proof yourself, but seems like it'd be better to just do a  single template statement with a only_if { node['nginx_resources']['service']['init_style'] == 'upstart' && node['nginx_resources']['service']['managed'] } no?

#Install the service definition, source an update cause a restart
#
if node['nginx_resources']['service']['managed']
  case node['nginx_resources']['service']['init_style']
  when 'upstart'
    template 'nginx_service' do
      path   '/etc/init/nginx.conf'
      source 'nginx-upstart.conf.erb'
      mode   '0644'
      variables({
        'sbin_path' => instance.sbin_path,
        'conf_path' => instance.conf_path,
        'pid_path'  => instance.pid_path,
        'configs'   => node['nginx_resources']['upstart'].to_hash
      })
    end
  end
end

**Comment by JonathanSerafini** [comment]
Ah well it's a question of runit really, which can't be arsed to follow the standard chef patterns ( that i've seen ). Upstart, Systemd, Rc.d and the like we can get around since they all use the service and template resources ( just different values ), but runit uses `runit_service` instead. Suppose could just not support runit though.

**Comment by JonathanSerafini** [comment]
Actually nevermind, i'll do as you recommend.

**Comment by JonathanSerafini** [comment]
Service updated in bedf3f3038e035a412831fa10602d44dd03207c4

**Comment by francoislapierremessier** [comment]
Site config additions/changes/deletes should trigger reloads in nginx instead of restarts

**Comment by JonathanSerafini** [comment]
Reload fixed in 1c5796c13593031901da394d62f1086d71289848

**Comment by JonathanSerafini** [comment]
User creation updated in 17e752de457687c466b09e8f782e09db85bdab2f

**Comment by JonathanSerafini** [comment]
Frank is no longer complaining ;)
